SET IGNORECASE TRUE;
DROP TABLE SCORING_USER CASCADE CONSTRAINT;
CREATE TABLE SCORING_USER(
   USERNAME VARCHAR2(50) NOT NULL PRIMARY KEY,
   PASSWORD VARCHAR2(50) NOT NULL,
   ENABLED VARCHAR2(1) NOT NULL
);
DROP TABLE SCORING_AUTHORITY CASCADE CONSTRAINT;
CREATE TABLE SCORING_AUTHORITY(
   USERNAME VARCHAR2(50) NOT NULL,
   AUTHORITY VARCHAR2(50) NOT NULL
);
CREATE UNIQUE INDEX IX_AUTH_USERNAME ON SCORING_AUTHORITY (USERNAME, AUTHORITY);

ALTER TABLE SCORING_AUTHORITY ADD CONSTRAINT FK_SCORING_AUTHORITY_USER FOREIGN KEY (USERNAME) REFERENCES SCORING_USER(USERNAME);

INSERT INTO SCORING_USER VALUES ('user1', '698d51a19d8a121ce581499d7b701668', 'Y'); --111
INSERT INTO SCORING_USER VALUES ('user2', 'bcbe3365e6ac95ea2c0343a2395834dd', 'Y');  --222
INSERT INTO SCORING_USER VALUES ('user3', '310dcbbf4cce62f762a2aaa148d556bd', 'Y');  --333

INSERT INTO SCORING_AUTHORITY VALUES ('user1', 'ROLE_USER');
INSERT INTO SCORING_AUTHORITY VALUES ('user1', 'ROLE_ADMIN');
INSERT INTO SCORING_AUTHORITY VALUES ('user2', 'ROLE_USER');
INSERT INTO SCORING_AUTHORITY VALUES ('user3', 'ROLE_USER');

COMMIT;